### PR TITLE
Add item to show outdated Homebrew formulae

### PR DESCRIPTION
**Pull request by hoop33**

### CODE REVIEW

**Comment by richie5um** [comment]
This is great, thanks!

**Comment by hoop33** [comment]
Not sure if you meant to do this, but this commit got merged out when the CrashPlan stuff got merged.

**Comment by richie5um** [comment]
Thanks. That wasn't intentional. I'll add it back.

-Rich

**Comment by richie5um** [comment]
Sorry. Now fixed. Thanks for noticing and letting me know. :-)

**Comment by hoop33** [comment]
I figured as much. Love this tool, BTW!

**Pull request merged**
